
get http://localhost:4000/internal/linkpreview/?url=https://www.yahoo.com
###
get http://localhost:4000/linkpreview/?url=https://yahoo.com


###
get http://localhost:4000/storeimage/?url=https://s.yimg.com/cv/apiv2/social/images/yahoo_default_logo.png